### ISSUE TITLE
Common functions. Finding players by name.

### ISSUE THREAD

**Issue by nthirtyone** [nthirtyone/avorion-scripts#7]
First note: I think we could move all common functions or possible common functions to one (or several) file in `scripts/lib/cmd/`. Such functions as `checkTable` (which should be renamed btw.) or function for finding player by name. In demo it was possible with just `findFaction()`, but currently for some reason it doesn't work. My guess is that it is related to Steam integration or upcoming alliance update.

If we move player finding function to external file we could use it in `inventory`, `whereis` and push it to `master`. If anything will change later then it will be way easier to adapt.

Hardly an issue, but it is a great way to discuss or communicate.

**Comment by mark-kubacki** [comment]
+1 from me.

Because `Galaxy():findFaction(<playerName>)` does not work anymore my quick hack has been to go through all factions starting from 1, because players get IDs with those (low) numbers.
https://github.com/wmark/aci-avorion-server/blob/7f840a47f154c2f6380ac07afedb047063904ac9/contrib/wmark/commands/whereis.lua#L4-L24

**Comment by nthirtyone** [comment]
Added in https://github.com/AvorionCommands/avorion-scripts/tree/new-commands/scripts/lib/cmd
